"""message

Revision ID: aafd88f53dde
Revises: bc678065bff1
Create Date: 2022-09-10 11:25:46.317469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aafd88f53dde'
down_revision = 'bc678065bff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teammates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('pronunciation', sa.String(length=80), nullable=False),
    sa.Column('pronouns', sa.String(length=80), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=True),
    sa.Column('q1_ans', sa.String(length=255), nullable=False),
    sa.Column('q2_ans', sa.String(length=255), nullable=False),
    sa.Column('q3_ans', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teammates')
    # ### end Alembic commands ###
